name: "LeanIX jenkins"
description: "Trigger Jenkins jobs"
inputs:
  jobBuildUrl:
    description: 'URL of job to be triggered (make sure to include /build or /buildWithParameters depending on your needs)'
    required: true
  parameters:
    description: 'Job parameters'
    required: false
runs:
  using: "node12"
  main: "dist/index.js"
