name: "LeanIX jenkins"
description: "Trigger Jenkins jobs"
inputs:
  jobUrl:
    description: 'URL of job to be triggered'
    required: true
  parameters:
    description: 'Job parameters'
    required: false
runs:
  using: "node12"
  main: "dist/index.js"
